# Generated by Django 2.2.2 on 2020-02-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotfind_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='LANDED', max_length=100)),
                ('lot_id', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
